#ifndef CPLUSPLUSTEST_COMMON_H
#define CPLUSPLUSTEST_COMMON_H

#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <algorithm>
#include <functional>
#include <utility>
#include <random>
#include <memory>
#include <cstring>
#include <string>
#include <array>
#include <vector>
#include <list>
#include <set>
#include <map>
#include <deque>
#include <queue>
#include <stack>
#include <unordered_set>
#include <unordered_map>

using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::array;
using std::vector;
using std::list;
using std::set;
using std::map;
using std::deque;
using std::queue;
using std::stack;
using std::unordered_set;
using std::unordered_map;
using std::priority_queue;

#endif //CPLUSPLUSTEST_COMMON_H
